package wanda.base.pojo.po;

public class Userjd {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERJD.ID
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERJD.MC
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String mc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERJD.DZ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String dz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERJD.YZBM
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String yzbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERJD.XLR
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String xlr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERJD.DH
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String dh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERJD.CZ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String cz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERJD.DZYX
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String dzyx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERJD.WZ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String wz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERJD.VCHAR1
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String vchar1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERJD.VCHAR2
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String vchar2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERJD.VCHAR3
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String vchar3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERJD.DQ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String dq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERJD.ID
     *
     * @return the value of USERJD.ID
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERJD.ID
     *
     * @param id the value for USERJD.ID
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERJD.MC
     *
     * @return the value of USERJD.MC
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERJD.MC
     *
     * @param mc the value for USERJD.MC
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setMc(String mc) {
        this.mc = mc == null ? null : mc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERJD.DZ
     *
     * @return the value of USERJD.DZ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getDz() {
        return dz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERJD.DZ
     *
     * @param dz the value for USERJD.DZ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setDz(String dz) {
        this.dz = dz == null ? null : dz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERJD.YZBM
     *
     * @return the value of USERJD.YZBM
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getYzbm() {
        return yzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERJD.YZBM
     *
     * @param yzbm the value for USERJD.YZBM
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setYzbm(String yzbm) {
        this.yzbm = yzbm == null ? null : yzbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERJD.XLR
     *
     * @return the value of USERJD.XLR
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getXlr() {
        return xlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERJD.XLR
     *
     * @param xlr the value for USERJD.XLR
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setXlr(String xlr) {
        this.xlr = xlr == null ? null : xlr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERJD.DH
     *
     * @return the value of USERJD.DH
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getDh() {
        return dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERJD.DH
     *
     * @param dh the value for USERJD.DH
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setDh(String dh) {
        this.dh = dh == null ? null : dh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERJD.CZ
     *
     * @return the value of USERJD.CZ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getCz() {
        return cz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERJD.CZ
     *
     * @param cz the value for USERJD.CZ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setCz(String cz) {
        this.cz = cz == null ? null : cz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERJD.DZYX
     *
     * @return the value of USERJD.DZYX
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getDzyx() {
        return dzyx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERJD.DZYX
     *
     * @param dzyx the value for USERJD.DZYX
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setDzyx(String dzyx) {
        this.dzyx = dzyx == null ? null : dzyx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERJD.WZ
     *
     * @return the value of USERJD.WZ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getWz() {
        return wz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERJD.WZ
     *
     * @param wz the value for USERJD.WZ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setWz(String wz) {
        this.wz = wz == null ? null : wz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERJD.VCHAR1
     *
     * @return the value of USERJD.VCHAR1
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getVchar1() {
        return vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERJD.VCHAR1
     *
     * @param vchar1 the value for USERJD.VCHAR1
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setVchar1(String vchar1) {
        this.vchar1 = vchar1 == null ? null : vchar1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERJD.VCHAR2
     *
     * @return the value of USERJD.VCHAR2
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getVchar2() {
        return vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERJD.VCHAR2
     *
     * @param vchar2 the value for USERJD.VCHAR2
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setVchar2(String vchar2) {
        this.vchar2 = vchar2 == null ? null : vchar2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERJD.VCHAR3
     *
     * @return the value of USERJD.VCHAR3
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getVchar3() {
        return vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERJD.VCHAR3
     *
     * @param vchar3 the value for USERJD.VCHAR3
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setVchar3(String vchar3) {
        this.vchar3 = vchar3 == null ? null : vchar3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERJD.DQ
     *
     * @return the value of USERJD.DQ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getDq() {
        return dq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERJD.DQ
     *
     * @param dq the value for USERJD.DQ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setDq(String dq) {
        this.dq = dq == null ? null : dq.trim();
    }
}