package wanda.base.pojo.po;

public class Useryy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.ID
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.MC
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String mc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.DZ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String dz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.YZBM
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String yzbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.DQ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String dq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.JB
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String jb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.CWS
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String cws;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.FYLJG
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String fyljg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.DH
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String dh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.YJKDH
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String yjkdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.LB
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String lb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.YPSR
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String ypsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.YWSR
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String ywsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.CZ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String cz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.VCHAR1
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String vchar1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.VCHAR2
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String vchar2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.VCHAR3
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String vchar3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.VCHAR4
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String vchar4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERYY.VCHAR5
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    private String vchar5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.ID
     *
     * @return the value of USERYY.ID
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.ID
     *
     * @param id the value for USERYY.ID
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.MC
     *
     * @return the value of USERYY.MC
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.MC
     *
     * @param mc the value for USERYY.MC
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setMc(String mc) {
        this.mc = mc == null ? null : mc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.DZ
     *
     * @return the value of USERYY.DZ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getDz() {
        return dz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.DZ
     *
     * @param dz the value for USERYY.DZ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setDz(String dz) {
        this.dz = dz == null ? null : dz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.YZBM
     *
     * @return the value of USERYY.YZBM
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getYzbm() {
        return yzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.YZBM
     *
     * @param yzbm the value for USERYY.YZBM
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setYzbm(String yzbm) {
        this.yzbm = yzbm == null ? null : yzbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.DQ
     *
     * @return the value of USERYY.DQ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getDq() {
        return dq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.DQ
     *
     * @param dq the value for USERYY.DQ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setDq(String dq) {
        this.dq = dq == null ? null : dq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.JB
     *
     * @return the value of USERYY.JB
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getJb() {
        return jb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.JB
     *
     * @param jb the value for USERYY.JB
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setJb(String jb) {
        this.jb = jb == null ? null : jb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.CWS
     *
     * @return the value of USERYY.CWS
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getCws() {
        return cws;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.CWS
     *
     * @param cws the value for USERYY.CWS
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setCws(String cws) {
        this.cws = cws == null ? null : cws.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.FYLJG
     *
     * @return the value of USERYY.FYLJG
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getFyljg() {
        return fyljg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.FYLJG
     *
     * @param fyljg the value for USERYY.FYLJG
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setFyljg(String fyljg) {
        this.fyljg = fyljg == null ? null : fyljg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.DH
     *
     * @return the value of USERYY.DH
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getDh() {
        return dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.DH
     *
     * @param dh the value for USERYY.DH
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setDh(String dh) {
        this.dh = dh == null ? null : dh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.YJKDH
     *
     * @return the value of USERYY.YJKDH
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getYjkdh() {
        return yjkdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.YJKDH
     *
     * @param yjkdh the value for USERYY.YJKDH
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setYjkdh(String yjkdh) {
        this.yjkdh = yjkdh == null ? null : yjkdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.LB
     *
     * @return the value of USERYY.LB
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getLb() {
        return lb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.LB
     *
     * @param lb the value for USERYY.LB
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setLb(String lb) {
        this.lb = lb == null ? null : lb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.YPSR
     *
     * @return the value of USERYY.YPSR
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getYpsr() {
        return ypsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.YPSR
     *
     * @param ypsr the value for USERYY.YPSR
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setYpsr(String ypsr) {
        this.ypsr = ypsr == null ? null : ypsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.YWSR
     *
     * @return the value of USERYY.YWSR
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getYwsr() {
        return ywsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.YWSR
     *
     * @param ywsr the value for USERYY.YWSR
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setYwsr(String ywsr) {
        this.ywsr = ywsr == null ? null : ywsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.CZ
     *
     * @return the value of USERYY.CZ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getCz() {
        return cz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.CZ
     *
     * @param cz the value for USERYY.CZ
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setCz(String cz) {
        this.cz = cz == null ? null : cz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.VCHAR1
     *
     * @return the value of USERYY.VCHAR1
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getVchar1() {
        return vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.VCHAR1
     *
     * @param vchar1 the value for USERYY.VCHAR1
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setVchar1(String vchar1) {
        this.vchar1 = vchar1 == null ? null : vchar1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.VCHAR2
     *
     * @return the value of USERYY.VCHAR2
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getVchar2() {
        return vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.VCHAR2
     *
     * @param vchar2 the value for USERYY.VCHAR2
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setVchar2(String vchar2) {
        this.vchar2 = vchar2 == null ? null : vchar2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.VCHAR3
     *
     * @return the value of USERYY.VCHAR3
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getVchar3() {
        return vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.VCHAR3
     *
     * @param vchar3 the value for USERYY.VCHAR3
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setVchar3(String vchar3) {
        this.vchar3 = vchar3 == null ? null : vchar3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.VCHAR4
     *
     * @return the value of USERYY.VCHAR4
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getVchar4() {
        return vchar4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.VCHAR4
     *
     * @param vchar4 the value for USERYY.VCHAR4
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setVchar4(String vchar4) {
        this.vchar4 = vchar4 == null ? null : vchar4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERYY.VCHAR5
     *
     * @return the value of USERYY.VCHAR5
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public String getVchar5() {
        return vchar5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERYY.VCHAR5
     *
     * @param vchar5 the value for USERYY.VCHAR5
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    public void setVchar5(String vchar5) {
        this.vchar5 = vchar5 == null ? null : vchar5.trim();
    }
}