package wanda.base.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import wanda.base.pojo.po.Useryy;
import wanda.base.pojo.po.UseryyExample;

public interface UseryyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    int countByExample(UseryyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    int deleteByExample(UseryyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    int insert(Useryy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    int insertSelective(Useryy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    List<Useryy> selectByExample(UseryyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    Useryy selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    int updateByExampleSelective(@Param("record") Useryy record, @Param("example") UseryyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    int updateByExample(@Param("record") Useryy record, @Param("example") UseryyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    int updateByPrimaryKeySelective(Useryy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated Wed Mar 22 10:46:08 CST 2017
     */
    int updateByPrimaryKey(Useryy record);
}